name: flutter_demo_auth
description: A simple demo auth app

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  shared_preferences: ^2.0.15
  equatable: ^2.0.3
  flutter_bloc: ^8.0.1
  loading_animation_widget: ^1.2.0+2
  formz: ^0.4.1
  flutter_svg: ^1.1.0
  mask_text_input_formatter: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  flutter_launcher_icons: ^0.9.3

flutter_icons:
  image_path: 'assets/icons/simple_auth.png'
  image_path_ios: 'assets/icons/simple_auth_ios.png'
  android: true
  ios: true

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Comfortaa
      fonts:
        - asset: assets/fonts/Comfortaa-Regular.ttf
          weight: 400
        - asset: assets/fonts/Comfortaa-Bold.ttf
          weight: 700
